# To create the environment:
# conda env create -f environment.yml
#
# To activate the environment:
# conda activate piquette
#
# To update the environment (if you modify this file):
# conda env update -f environment.yml

name: vending-machine
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11
  
  # Pip-only packages
  - pip
  - pip:
    - aiohttp==3.11.11
    - brightdata-sdk==1.0.5
    - requests==2.32.3
    - pydantic>=2.11.7,<3.0.0
    - python-decouple==3.8
    - typing-extensions==4.14.1
    - certifi==2025.6.15
    - google-generativeai==0.8.3
    - google-api-core==2.24.1
    - asyncpraw==7.8.1
    - asyncprawcore==2.4.0
    - supabase==2.17.0
    - fastapi==0.115.6
    - uvicorn[standard]==0.32.1